### ISSUE TITLE
Windows rules rework

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#324]
This issue attempts to redesign and restructure the Windows rules for Eventchannel. It consists of several steps which allow us to make it easier to work and understand the new Windows ruleset.

### Tasks

- [x] Create rules for the Application channel. _Done:_ https://github.com/wazuh/wazuh-ruleset/pull/317

- [x] Reassign the range ID for Windows rules (60000 - 69999) _Done:_ https://github.com/wazuh/wazuh-ruleset/pull/317

- [x] Rework of rules for the System channel

- [x] Classification of Windows rules by channel (creating a rules file for each one).
  - [x] Security
  - [x] System
  - [x] Application
  - [x] Sysmon
  - [x] Windows Defender
  - [x] mcAfee
  - [x] Windows logs
  - [x] MSE
  - [x] IPSec

- [x] Document the new Windows ruleset

**Comment by chemamartinez** [comment]
Working on branch [eventchannel-rework](https://github.com/wazuh/wazuh-ruleset/tree/eventchannel-rework)

**Comment by cristgl** [comment]
Relevant information about some events:

TS Gateway rules included at the System group rules don't belong to that channel, but to `Microsoft-Windows-TerminalServices`. Also, events related to `RemoteAccess` are generated when the system has promoted to a domain controller at the `File Replication Service` channel.

Besides, it would be nice to classify the next rules that don't belong to any channel:

```
  <rule id="60116" level="10" frequency="$MS_FREQ" timeframe="240">
    <if_matched_sid>60003</if_matched_sid>
    <description>Multiple Windows error events</description>
    <options>no_full_log</options>
  </rule>

  <rule id="60117" level="10" frequency="$MS_FREQ" timeframe="120">
    <if_matched_sid>60002</if_matched_sid>
    <description>Multiple Windows WARNING events</description>
    <options>no_full_log</options>
  </rule>
```

**Comment by chemamartinez** [comment]
IPSec rules are a subsection of Security rules: https://support.microsoft.com/en-us/help/977519/description-of-security-events-in-windows-7-and-in-windows-server-2008. They have been added to `0600-win-security_rules.xml`.

**Comment by cristgl** [comment]
Issue related to Sysmon rules
--------------------------------------

With the current rules structure, a Sysmon process creation event should follow the next rule flow: 60000, 60001, 60008, 61600, 61603. But instead, the flow is: 60000, 60001, showing a Windows generic informational event of level 0. 

This structure is followed by each event of every other channel, which generates the correct alerts without further problems. When changing the `if_sid` of the rule 60008 to 60001 instead of 60000, the flow taken is the right one, but it should also be taken in the other case.
