### ISSUE TITLE
Enrich new policy files for the Configuration Assessment scanner

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#373]
From Wazuh v3.9.0, the policy files managed by Rootcheck were translated to YAML format and enriched with the CIS benchmarks (if possible) for each OS and target.

Those new policies can be found [here](https://github.com/wazuh/wazuh-ruleset/tree/3.9/configuration-assessment).

We have to continue creating new policy files which allow the Configuration Assessment scanner to be supported in more OS and for more purposes. Here we have a brief of the main tasks and policies we have to achieve:

- [ ] Policy files created by @Bob-Andrews for Windows Server 2016: https://github.com/wazuh/wazuh-ruleset/pull/265
- [x] [cis_win2012r2_memberL2_rcl.txt](https://github.com/wazuh/wazuh-ruleset/blob/3.9/rootchecks/cis_win2012r2_memberL2_rcl.txt)
- [x] Imported policy files from Rootcheck at https://github.com/wazuh/wazuh/pull/1941.

## Update

Working on branch [import-sca-policies](https://github.com/wazuh/wazuh/tree/import-sca-policies).

It has been imported the following policies files from OSSEC:

- acsc_office2016_rcl.txt
- cis_debianlinux7-8_L1_rcl.txt
- cis_debianlinux7-8_L2_rcl.txt
- cis_solaris11_rcl.txt
- cis_win10_enterprise_L1_rcl.txt
- cis_win10_enterprise_L2_rcl.txt
- system_audit_pw.txt

Remaining policy files:

- Windows Server 2016 policy files: Added at https://github.com/wazuh/wazuh-ruleset/pull/265

## Subtasks

- [x] Store the imported policies into the SCA folders (`etc/sca/`).
- [x] Translate the policies to YAML format.
- [x] Enrich policy files with CIS benchmarks.

**Comment by chemamartinez** [comment]
There exists a CIS policy for Amazon Web Services which has to be adapted to our SCA policies ASAP:
https://d1.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf

**Comment by agnutzmann** [comment]
> I translated the remaining files to YAML and stored them in their respective folders. All that remains is to enrich the files, right now working on the Windows Enterprise L1 one.

Did you translate the cis_win2016_member files?
I'm asking because i'm translating them right now (it is a work in progress). I'm, trying to understand how to share it.

**Comment by chemamartinez** [comment]
Hi @agnutzmann,

As I explained you [here](https://github.com/wazuh/wazuh-ruleset/pull/265#issuecomment-529451846), you could share the developed policies by a pull request to the repo. If you have troubles to do it, don't hesitate to ask us about it.

Let me close the issue, it will be overwritten by https://github.com/wazuh/wazuh-ruleset/issues/485.

Regards.

**Comment by maxicloud** [comment]
Hello,

Do you have cis windows server 2019?

**Comment by maxicloud** [comment]
@juan70 @Leamsy @chemamartinez @agnutzmann 
Hello,

Do you have cis windows server 2019?
