### ISSUE TITLE
Map rules to NIST 800-53 standard

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-ruleset#394]
This issue is similar to #392.

Taking advantage of current PCI DSS mapping and NIST 800-53 equivalences, we can map the current ruleset to [NIST 800-53 Security Control Catalog](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf), according to the following table:

| PCI DSS 3.0                             | NIST 800-53                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2,4                                     | CA-7: Continuous Monitoring<br> CM-8: Information System Component Inventory<br> IA-3: Device Identification and Authentication<br> SA-4: Acquisition Process<br> SC-17: Public Key Infrastructure Certificates<br> SI-4: Information System Monitoring<br> PM-5: Information System Inventory                                                                                                                                                                                                                                                                                                                                            |
| 2,4                                     | CA-7: Continuous Monitoring<br> CM-2: Baseline Configuration<br> CM-8: Information System Component Inventory<br> CM-10: Software Usage Restrictions<br> CM-11: User-Installed Software<br> SA-4: Acquisition Process<br> SC-18: Mobile Code<br> SC-34: Non-Modifiable Executable Programs<br> SI-4: Information System Monitoring<br> PM-5: Information System Inventory                                                                                                                                                                                                                                                                 |
| 6.1<br> 6.2<br> 11.2                    | CA-2: Security Assessments<br> CA-7: Continuous Monitoring<br> RA-5: Vulnerability Scanning<br> SC-34: Non-Modifiable Executable Programs<br> SI-4: Information System Monitoring<br> SI-7: Software, Firmware, and Information Integrity                                                                                                                                                                                                                                                                                                                                                                                                 |
| 2.1<br> 7.1 - 7.3<br> 8.1 - 8.3<br> 8.7 | AC-2: Account Management<br> AC-6: Least Privilege<br> AC-17: Remote Access<br> AC-19: Access Control for Mobile Devices<br> CA-7: Continuous Monitoring<br> IA-2: Identification and Authentication (Organizational Users)<br> IA-4: Identifier Management<br> IA-5: Authenticator Management<br> SI-4: Information System Monitoring                                                                                                                                                                                                                                                                                                    |
| 2.2<br> 2.3<br> 6.2<br> 11.5            | CA-7: Continuous Monitoring<br> CM-2: Baseline Configuration<br> CM-3: Configuration Change Control<br> CM-5: Access Restrictions for Change<br> CM-6: Configuration Settings<br> CM-7: Least Functionality<br> CM-8: Information System Component Inventory<br> CM-9: Configuration Management Plan<br> CM-11: User-Installed Software<br> MA-4: Nonlocal Maintenance<br> RA-5: Vulnerability Scanning<br> SA-4: Acquisition Process<br> SC-15: Collaborative Computing Devices<br> SC-34: Non-Modifiable Executable Programs<br> SI-2: Flaw Remediation<br> SI-4: Information System Monitoring                                         |
| 10.1 - 10.9                             | AC-23: Data Mining Protection<br> AU-2: Audit Events<br> AU-3: Content of Audit Records<br> AU-4: Audit Storage Capacity<br> AU-5: Response to Audit Processing Failures<br> AU-6: Audit Review, Analysis, and Reporting<br> AU-7: Audit Reduction and Report Generation<br> AU-8: Time Stamps<br> AU-9: Protection of Audit Information<br> AU-10: Non-repudiation<br> AU-11: Audit Record Retention<br> AU-12: Audit Generation<br> AU-13: Monitoring for Information Disclosure<br> AU-14: Session Audit<br> CA-7: Continuous Monitoring<br> IA-10: Adaptive Identification and Authentication<br> SI-4: Information System Monitoring |
| 2.2<br> 2.3<br> 6.2<br> 11.5            | CA-7: Continuous Monitoring<br> CM-2: Baseline Configuration<br> CM-3: Configuration Change Control<br> CM-5: Access Restrictions for Change<br> CM-6: Configuration Settings<br> CM-7: Least Functionality<br> CM-8: Information System Component Inventory<br> CM-9: Configuration Management Plan<br> CM-11: User-Installed Software<br> MA-4: Nonlocal Maintenance<br> RA-5: Vulnerability Scanning<br> SA-4: Acquisition Process<br> SC-15: Collaborative Computing Devices<br> SC-34: Non-Modifiable Executable Programs<br> SI-2: Flaw Remediation<br> SI-4: Information System Monitoring                                         |
| 5.1 - 5.4                               | CA-7: Continuous Monitoring<br> SC-39: Process Isolation<br> SC-44: Detonation Chambers<br> SI-3: Malicious Code Protection<br> SI-4: Information System Monitoring<br> SI-8: Spam Protection                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 1,4                                     | AC-4: Information Flow Enforcement<br> CA-7: Continuous Monitoring<br> CA-9: Internal System Connections<br> CM-2: Baseline Configuration<br> CM-6: Configuration Settings<br> CM-8: Information System Component Inventory<br> SC-20: Secure Name /Address Resolution Service (Authoritative Source)<br> SC-21: Secure Name /Address Resolution Service (Recursive or Caching Resolver)<br> SC-22: Architecture and Provisioning for Name/Address Resolution Service<br> SC-41: Port and I/O Device Access<br> SI-4: Information System Monitoring                                                                                       |
| 4.3<br> 9.5 - 9.7                       | CP-9: Information System Backup<br> CP-10: Information System Recovery and Reconstitution<br> MP-4: Media Storage                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 1.1 - 1.2<br> 2.2<br> 6.2               | AC-4: Information Flow Enforcement<br> CA-3: System Interconnections<br> CA-7: Continuous Monitoring<br> CA-9: Internal System Connections<br> CM-2: Baseline Configuration<br> CM-3: Configuration Change Control<br> CM-5: Access Restrictions for Change<br> CM-6: Configuration Settings<br> CM-8: Information System Component Inventory<br> MA-4: Nonlocal Maintenance<br> SC-24: Fail in Known State<br> SI-4: Information System Monitoring                                                                                                                                                                                       |
| 1.1 - 1.3<br> 8.3<br> 10.9<br> 11.4     | AC-4: Information Flow Enforcement<br> AC-17: Remote Access<br> AC-20: Use of External Information Systems<br> CA-3: System Interconnections<br> CA-7: Continuous Monitoring<br> CA-9: Internal System Connections<br> CM-2: Baseline Configuration<br> SA-9: External Information System Services<br> SC-7: Boundary Protection<br> SC-8: Transmission Confidentiality and Integrity<br> SI-4: Information System Monitoring                                                                                                                                                                                                             |
| 3.6<br> 4.1 - 4.3                       | AC-3: Access Enforcement<br> AC-4: Information Flow Enforcement<br> AC-23: Data Mining Protection<br> CA-7: Continuous Monitoring<br> CA-9: Internal System Connections<br> IR-9: Information Spillage Response<br> MP-5: Media Transport<br> SA-18: Tamper Resistance and Detection<br> SC-8: Transmission Confidentiality and Integrity<br> SC-28: Protection of Information at Rest<br> SC-31: Covert Channel Analysis<br> SC-41: Port and I/O Device Access<br> SI-4: Information System Monitoring                                                                                                                                   |
| 1.3 - 1.4<br> 4.3<br> 7.1 - 7.3<br> 8.7 | AC-1: Access Control Policy and Procedures<br> AC-2: Account Management<br> AC-3: Access Enforcement<br> AC-6: Least Privilege<br> AC-24: Access Control Decisions<br> CA-7: Continuous Monitoring<br> MP-3: Media Marking<br> RA-2: Security Categorization<br> SC-16: Transmission of Security Attributes<br> SI-4: Information System Monitoring                                                                                                                                                                                                                                                                                       |
| 4.3<br> 11.1                            | AC-18: Wireless Access<br> AC-19: Access Control for Mobile Devices<br> CA-3: System Interconnections<br> CA-7: Continuous Monitoring<br> CM-2: Baseline Configuration<br> IA-3: Device Identification and Authentication<br> SC-8: Transmission Confidentiality and Integrity<br> SC-17: Public Key Infrastructure Certificates<br> SC-40: Wireless Link Protection<br> SI-4: Information System Monitoring                                                                                                                                                                                                                              |
| 7.1 - 7.3<br> 8.7 - 8.8                 | AC-2: Account Management<br> AC-3: Access Enforcement<br> AC-7: Unsuccessful Logon Attempts<br> AC-11: Session Lock<br> AC-12: Session Termination<br> CA-7: Continuous Monitoring<br> IA-5: Authenticator Management<br> IA-10: Adaptive Identification and Authentication<br> SC-17: Public Key Infrastructure Certificates<br> SC-23: Session Authenticity<br> SI-4: Information System Monitoring                                                                                                                                                                                                                                     |
| 12,6                                    | AT-1: Security Awareness and Training Policy and Procedures<br> AT-2: Security Awareness Training<br> AT-3: Role-Based Security Training<br> AT-4: Security Training Records<br> SA-11: Developer Security Testing and Evaluation<br> SA-16: Developer-Provided Training<br> PM-13: Information Security Workforce<br> PM-14: Testing, Training, & Monitoring<br> PM-16: Threat Awareness Program                                                                                                                                                                                                                                         |
| 6.3<br> 6.5 - 6.7                       | SA-13: Trustworthiness<br> SA-15: Development Process, Standards, and Tools<br> SA-16: Developer-Provided Training<br> SA-17: Developer Security Architecture and Design<br> SA-20: Customized Development of Critical Components<br> SA-21: Developer Screening<br> SC-39: Process Isolation<br> SI-10: Information Input Validation<br> SI-11: Error Handling<br> SI-15: Information Output Filtering<br> SI-16: Memory Protection                                                                                                                                                                                                      |
| 12.10                                   | IR-1: Incident Response Policy and Procedures<br> IR-2: Incident Response Training<br> IR-3: Incident Response Testing<br> IR-4: Incident Handling<br> IR-5: Incident Monitoring<br> IR-6: Incident Reporting<br> IR-7: Incident Response Assistance<br> IR-8: Incident Response Plan<br> IR-10: Integrated Information Security Analysis Team                                                                                                                                                                                                                                                                                            |
| 11,3                                    | CA-2: Security Assessments<br> CA-5: Plan of Action and Milestones<br> CA-6: Security Authorization<br> CA-8: Penetration Testing<br> RA-6: Technical Surveillance Countermeasures Survey<br> SI-6: Security Function Verification<br> PM-6: Information Security Measures of Performance<br> PM-14: Testing, Training, & Monitoring                                                                                                                                                                                                                                                                                                      |

Tasks:
- [x] Get equivalences 1-to-1 from PCI DSS to NIST 800-53 using ruleset naming convention
- [x] Run Python script developed in #392 
- [x] Once mapping is done, review and test rules are applied properly

**Comment by crd1985** [comment]
# Status update
## Summary
Currently, performing mapping between PCI DSS and NIST 800 53. Slowly due to manual process and further reading. The mapping table is quite difuse.

## Tasks
* Reading standards and finding equivalences to translate into mapping.

## Difficulties
* Slowly reading process. Large standard definitions.

## Pending
* Finishing mapping (about 25% to complete the task)
* Execute python script to edit ruleset automatically

**Comment by crd1985** [comment]
Just sharing the mapping:
```json
{
  "pci_dss_1.1.1": "nist_800_53_CM.3",
  "pci_dss_1.3.4": "nist_800_53_CA.3,nist_800_53_SC.7",
  "pci_dss_1.4": "nist_800_53_SC.7",
  "pci_dss_10.1": "nist_800_53_AU.1",
  "pci_dss_10.2.1": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.2.2": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.2.4": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.2.5": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.2.6": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.2.7": "nist_800_53_AU.3.1,nist_800_53_IA.10",
  "pci_dss_10.4": "nist_800_53_AU.8",
  "pci_dss_10.5.2": "nist_800_53_AU.9",
  "pci_dss_10.5.5": "nist_800_53_AU.9",
  "pci_dss_10.6": "nist_800_53_AU.6",
  "pci_dss_10.6.1": "nist_800_53_AU.6",
  "pci_dss_11.4": "nist_800_53_SC.7",
  "pci_dss_11.5": "nist_800_53_SI.7",
  "pci_dss_2.2": "nist_800_53_CM.1",
  "pci_dss_2.2.3": "nist_800_53_CM.1",
  "pci_dss_4.1": "nist_800_53_SC.8",
  "pci_dss_5.1": "nist_800_53_SI.5",
  "pci_dss_5.2": "nist_800_53_SI.5",
  "pci_dss_6.2": "nist_800_53_MA.2",
  "pci_dss_6.5": "nist_800_53_SA.11",
  "pci_dss_6.5.1": "nist_800_53_SA.11",
  "pci_dss_6.5.10": "nist_800_53_SA.11",
  "pci_dss_6.5.2": "nist_800_53_SA.11",
  "pci_dss_6.5.5": "nist_800_53_SA.11",
  "pci_dss_6.5.7": "nist_800_53_SA.11",
  "pci_dss_6.5.8": "nist_800_53_SA.11",
  "pci_dss_6.6": "nist_800_53_SI.10,nist_800_53_SI.11,nist_800_53_SI.15,nist_800_53_SI.16",
  "pci_dss_8.1.2": "nist_800_53_AC.2,nist_800_53_IA.4",
  "pci_dss_8.1.4": "nist_800_53_AC.2",
  "pci_dss_8.1.5": "nist_800_53_AC.2",
  "pci_dss_8.1.6": "nist_800_53_AC.7",
  "pci_dss_8.1.8": "nist_800_53_AC.12",
  "pci_dss_8.2.4": "nist_800_53_IA.5",
  "pci_dss_8.7": "nist_800_53_SC.2"
}
```

**Comment by crd1985** [comment]
Need to improve NIST mapping.

**Comment by crd1985** [comment]
This is the improved version of the mapping:
```
{
  "pci_dss_1.1.1": "nist_800_53_CM.3,nist_800_53_CM.5",
  "pci_dss_1.3.4": "nist_800_53_CA.3",
  "pci_dss_1.4": "nist_800_53_SC.7",
  "pci_dss_10.1": "nist_800_53_AU.12",
  "pci_dss_10.2.1": "nist_800_53_IA.10",
  "pci_dss_10.2.2": "nist_800_53_IA.10,nist_800_53_AC.6",
  "pci_dss_10.2.4": "nist_800_53_IA.10,nist_800_53_AC.7",
  "pci_dss_10.2.5": "nist_800_53_IA.10,nist_800_53_AC.7",
  "pci_dss_10.2.6": "nist_800_53_IA.10,nist_800_53_AU.5",
  "pci_dss_10.2.7": "nist_800_53_IA.10",
  "pci_dss_10.4": "nist_800_53_AU.8",
  "pci_dss_10.5.2": "nist_800_53_AU.9",
  "pci_dss_10.5.5": "nist_800_53_AU.9",
  "pci_dss_10.6": "nist_800_53_AU.6",
  "pci_dss_10.6.1": "nist_800_53_AU.6",
  "pci_dss_11.4": "nist_800_53_IA.10",
  "pci_dss_11.5": "nist_800_53_SI.7",
  "pci_dss_2.2": "nist_800_53_CM.1",
  "pci_dss_2.2.3": "nist_800_53_CM.1",
  "pci_dss_4.1": "nist_800_53_SC.8",
  "pci_dss_5.1": "nist_800_53_SI.3",
  "pci_dss_5.2": "nist_800_53_SI.3",
  "pci_dss_6.2": "nist_800_53_SI.2",
  "pci_dss_6.5": "nist_800_53_SA.11",
  "pci_dss_6.5.1": "nist_800_53_SA.11",
  "pci_dss_6.5.10": "nist_800_53_SA.11",
  "pci_dss_6.5.2": "nist_800_53_SA.11",
  "pci_dss_6.5.5": "nist_800_53_SA.11",
  "pci_dss_6.5.7": "nist_800_53_SA.11",
  "pci_dss_6.5.8": "nist_800_53_SA.11",
  "pci_dss_8.1.2": "nist_800_53_AC.2,nist_800_53_IA.4",
  "pci_dss_8.1.4": "nist_800_53_AC.2",
  "pci_dss_8.1.5": "nist_800_53_AC.2",
  "pci_dss_8.1.6": "nist_800_53_AC.7",
  "pci_dss_8.1.8": "nist_800_53_AC.12",
  "pci_dss_8.2.4": "nist_800_53_IA.5",
  "pci_dss_8.7": "nist_800_53_SC.2"
}
```

The next step will be resetting the nist rules and re-run the script to edit the ruleset.

**Comment by crd1985** [comment]
Need to update to the following improved mapping:
```
{
  "pci_dss_1.1.1": "nist_800_53_CM.3,nist_800_53_CM.5",
  "pci_dss_1.3.4": "nist_800_53_CA.3",
  "pci_dss_1.4": "nist_800_53_SC.7",
  "pci_dss_10.1": "nist_800_53_AU.12",
  "pci_dss_10.2.1": "nist_800_53_AU.14",
  "pci_dss_10.2.2": "nist_800_53_AU.14,nist_800_53_AC.6",
  "pci_dss_10.2.4": "nist_800_53_AU.14,nist_800_53_AC.7",
  "pci_dss_10.2.5": "nist_800_53_AU.14,nist_800_53_AC.7",
  "pci_dss_10.2.6": "nist_800_53_AU.14,nist_800_53_AU.5",
  "pci_dss_10.2.7": "nist_800_53_AU.14",
  "pci_dss_10.4": "nist_800_53_AU.8",
  "pci_dss_10.5.2": "nist_800_53_AU.9",
  "pci_dss_10.5.5": "nist_800_53_AU.9",
  "pci_dss_10.6": "nist_800_53_AU.6",
  "pci_dss_10.6.1": "nist_800_53_AU.6",
  "pci_dss_11.4": "nist_800_53_SI.4",
  "pci_dss_11.5": "nist_800_53_SI.7",
  "pci_dss_2.2": "nist_800_53_CM.1",
  "pci_dss_2.2.3": "nist_800_53_CM.1",
  "pci_dss_4.1": "nist_800_53_SC.8",
  "pci_dss_5.1": "nist_800_53_SI.3",
  "pci_dss_5.2": "nist_800_53_SI.3",
  "pci_dss_6.2": "nist_800_53_SI.2",
  "pci_dss_6.5": "nist_800_53_SA.11",
  "pci_dss_6.5.1": "nist_800_53_SA.11",
  "pci_dss_6.5.10": "nist_800_53_SA.11",
  "pci_dss_6.5.2": "nist_800_53_SA.11",
  "pci_dss_6.5.5": "nist_800_53_SA.11",
  "pci_dss_6.5.7": "nist_800_53_SA.11",
  "pci_dss_6.5.8": "nist_800_53_SA.11",
  "pci_dss_8.1.2": "nist_800_53_AC.2,nist_800_53_IA.4",
  "pci_dss_8.1.4": "nist_800_53_AC.2",
  "pci_dss_8.1.5": "nist_800_53_AC.2",
  "pci_dss_8.1.6": "nist_800_53_AC.7",
  "pci_dss_8.1.8": "nist_800_53_AC.12",
  "pci_dss_8.2.4": "nist_800_53_IA.5",
  "pci_dss_8.7": "nist_800_53_SC.2",
  "pci_dss_2.2.2": "nist_800_53_CM.1",
  "pci_dss_2.2.4": "nist_800_53_CM.1",
  "pci_dss_6.6": "nist_800_53_SC5,nist_800_53_SI.3"
}```
